CREATEDATABASE IFNOTEXISTSlab_mgm;
USE lab_mgm;
CREATETABLEvisitors(
idINTAUTO_INCREMENTPRIMARYKEY,
namaVARCHAR(255)NOTNULL,
instansiVARCHAR(255)NOTNULL,
kontakVARCHAR(255)NOTNULL,
pic_labVARCHAR(255)NOTNULL,
tujuanVARCHAR(50)NOTNULL,
tujuan_customVARCHAR(255)DEFAULTNULL,
created_atTIMESTAMPDEFAULTCURRENT_TIMESTAMP
);
